### PR TITLE
Reduce exports from SotoSignerV4

### PR DESCRIPTION
**Pull request by adam-fowler**

### CODE REVIEW

**Review by 0xTim — APPROVED** [review]
Reducing exports is always good - is there any reason why these are needed at all for v7?

**Comment by adam-fowler** [comment]
> Reducing exports is always good - is there any reason why these are needed at all for v7?

I think it is a good idea to export the symbols my public APIs use. Makes it easier for the end user.

**Comment by 0xTim** [comment]
Oh completely agree - are things like ByteBuffer going to be part of the public API though?

(This is a more general question as opposed to being specifically about this PR, I know removing all the future APIs is a multi step process)

**Comment by adam-fowler** [comment]
ByteBuffer is part of the public API. I don't think that is going to change. Unless we get the bag of bytes type in the sodlib

**Comment by 0xTim** [comment]
🤦‍♂️ travel brain getting futures and byte buffers mixed up

**Pull request merged**
