### PR TITLE
Add .spi.yml to point to correct documentation

### PR DESCRIPTION
**Pull request by adam-fowler**
Add .spi.yml to get Swift Package Index to add documentation link

### CODE REVIEW

**Comment by adam-fowler** [comment]
@finestructure is this correct?

**Comment by finestructure** [comment]
The syntax is correct but it looks like you copied this with curly quotes instead of `"` – from our announcement post! I need to fix that!

**Review by 0xTim — CHANGES_REQUESTED** [review]
As @finestructure said

**Comment by adam-fowler** [comment]
> As @finestructure said

fixed

**Review by 0xTim — APPROVED** [review]
👍

**Pull request merged**
